### ISSUE TITLE
MySQL密码更新流程 未加入 iam 密码更改

### ISSUE THREAD

**Issue by lvtu0316** [TencentBlueKing/BKDocs#134]
关闭相关服务
# 关闭平台服务
```
echo bkdata gse job paas gse kafka cmdb iam | xargs -n 1 ./bkcec stop
echo bkdata gse job paas gse kafka cmdb  iam | xargs -n 1 ./bkcec status
```

重新生成配置
和mysql相关的模块为mysql，paas，job，bkdata，saas，iam

`echo mysql paas job bkdata iam | xargs -n 1 ./bkcec render`

重新启动平台
`echo paas gse cmdb kafka job bkdata iam | xargs -n 1 ./bkcec start`

重新初始化APPO
# 在中控机
```
./bkcec stop appo
./bkcec initdata appo
./bkcec start appo
./bkcec activate appo
```

**Comment by TencentBlueKing** [comment]
Thanks, your suggestion has been accepted
