### ISSUE TITLE
新文档中心无法打开各主题内容，提示404。 

### ISSUE THREAD

**Issue by jona95** [TencentBlueKing/BKDocs#158]
新文档中心https://bk.tencent.com/docs_new，点击访问“快速入门”、“部署维护”等各个主题，均无法打开显示内容，显示404页面。

联系qq：653151751

**Comment by TencentBlueKing** [comment]
用户您好，根据后台查询，您访问的是社区版英文文档，英文文档暂时还没有撰写。
https://bk.tencent.com/docs_new/ 最下角将英文改为中文即可。
谢谢您的参与。
