### ISSUE TITLE
蓝鲸监控产品结构图改进建议

### ISSUE THREAD

**Issue by jona95** [TencentBlueKing/BKDocs#159]
建议改进的文章位置：BKDocs/ZH/5.1/蓝鲸监控/产品结构图/Product_Architecture.md 
蓝鲸监控产品结构图中，缺少描述说明被监控客户端部署哪些模块和服务，只是描述了监控大概的数据流转的结构。没有像Prometheus那样用结构图清晰的描述出来服务端和客户端都分别部署哪些组件和服务模块。
例如，看了Prometheus的结构图，可以很快速的知道，有各种exporter模块部署到被监控服务器上，进行数据采集、指标暴漏输出。
联系qq：653151751

**Comment by TencentBlueKing** [comment]
用户您好，非常感谢您的建议，助手已经将您宝贵的建议已反馈蓝鲸监控的产品经理，期待您更多宝贵的建议。
