### ISSUE TITLE
部署维护里没有找到如何容灾方式部署蓝鲸平台系统的说明

### ISSUE THREAD

**Issue by jona95** [TencentBlueKing/BKDocs#160]
查看的文档目录：BKDocs/ZH/5.1/部署维护/
在部署维护目录的内容里，没有找到如何以容灾的方式部署我的蓝鲸平台。目前多台机器的部署也是只部署单服务和数据文件，如果有机器宕机或着损坏，那么部署其上的相应服务就会瘫痪。
建议蓝鲸给出容灾部署的方案。

联系qq：653151751

**Comment by shpdnkti** [comment]
感觉你的建议，暂时未有计划提供社区版的容灾部署方案。
