### ISSUE TITLE
节点管理-附录-手动安装agent

### ISSUE THREAD

**Issue by liu-xiwang** [TencentBlueKing/BKDocs#188]
节点管理-附录-手动安装agent 下有四级标题。 因为前端一些逻辑只支持到三级标题，所以这里会触发一些 bug。

![image](https://user-images.githubusercontent.com/52487299/72045273-ac270680-32f0-11ea-9bc5-075a58ca0535.png)

**bug：**
1. 点击四级标题是，左侧目录会收缩。
2. 有其他位置的连接是到四级标题是，左侧目录同样不会展开。
3. 四级标题的父标题不会有箭头标识（标识有子标题）。

**解决方法：**
- 将四级标题的内容移动到三级标题下。
- 前端修改支持该逻辑。

**Comment by TencentBlueKing** [comment]
前端已支持该逻辑，正在测试中
