### ISSUE TITLE
ITSM图片序号错误&学习视频建议

### ISSUE THREAD

**Issue by cheunghang-zhang** [TencentBlueKing/BKDocs#202]
**1.ITSM > 流程管理（后台）-图片序号错误**
25跳27，28重复，部分缺失等。
建议取消序号，或者整体调整图片顺序。
![image](https://user-images.githubusercontent.com/56474473/74721538-863b3d00-5272-11ea-82ec-3cb0db61eb52.png)

**2.开发指南 > 学习视频**

![image](https://user-images.githubusercontent.com/56474473/74721670-b84c9f00-5272-11ea-9f2e-5c7b9a20a20e.png)

链接腾讯云大学-专业课程概述无目录无大纲无发看到其他学习视频
建议链到文档中心-视频教程，或https://cloud.tencent.com/edu/learning/major-100008

**Comment by TencentBlueKing** [comment]
谢谢同学您的建议，已采纳，请查收
ITSM图例修改
https://bk.tencent.com/docs/document/5.1/22/3776
SaaS开发视频修改
https://bk.tencent.com/docs/document/5.1/19/579
