### ISSUE TITLE
部署维护-基础包安装-环境验证

### ISSUE THREAD

**Issue by huangtao1** [TencentBlueKing/BKDocs#209]
#### 3. 检查 BKDATA 运行状态

#从中控机中跳转到 BKDATA Svr，执行检查脚本检查接口，无报错即正常

ssh $BKDATA_IP

此处$BKDATA_IP应该是`bkdata(dataapi)`服务所在的机器ip

**Comment by TencentBlueKing** [comment]
同学感谢您的积极参与，$BKDATA_IP,bkdata(dataapi)服务所在的机器ip 已经写入配置文件当中，所以

**Comment by huangtao1** [comment]
> 同学感谢您的积极参与，$BKDATA_IP,bkdata(dataapi)服务所在的机器ip 已经写入配置文件当中，所以ssh $BKDATA_IP，是没问题的

您好，我现在5.1.26获取出来的IP是不对的，获取出来是bkdata(databus)的ip

**Comment by huangtao1** [comment]
> 同学感谢您的积极参与，$BKDATA_IP,bkdata(dataapi)服务所在的机器ip 已经写入配置文件当中，所以ssh $BKDATA_IP，是没问题的

您好，我现在5.1.26获取出来的IP是不对的，获取出来是bkdata(databus)的ip

**Comment by TencentBlueKing** [comment]
该问题请在社区群495299374，反馈。如果已满，请加878501914
