### ISSUE TITLE
单机部署一键安装报错 /usr/bin/ld: cannot find -lmysqlclient 导致安装任务终止

### ISSUE THREAD

**Issue by zjcnew** [TencentBlueKing/BKDocs#227]
全新的CentOS7.7.1908环境，单机部署，部署全组件，一键部署，
$ cd /data/install
$ ./install_minibk -y
最终出现以下报错。

    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    running build_ext
    building '_mysql' extension
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/include/mysql -I/opt/py27/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/_mysql.o -L/usr/lib -lmysqlclient -lpthread -lm -lrt -ldl -o build/lib.linux-x86_64-2.7/_mysql.so
    /usr/bin/ld: cannot find -lmysqlclient
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/data/bkce/.envs/bkdata-dataapi/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HehP_y/MySQL-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ImHGrh-record/install-record.txt --single-version-externally-managed --compile --install-headers /data/bkce/.envs/bkdata-dataapi/include/site/python2.7/MySQL-python" failed with error code 1 in /tmp/pip-build-HehP_y/MySQL-python/

![企业微信截图_20200508110335](https://user-images.githubusercontent.com/22335594/81368208-c1d2fe00-9121-11ea-9fbe-036eeefa8c5a.png)

我的解决方式：
export LDFLAGS=-L/data/bkce/service/mysql/lib
/data/bkce/.envs/bkdata-dataapi/bin/pip install MySQL-python==1.2.5

望修复！

**Comment by shpdnkti** [comment]
感谢你的反馈，问题已经在社区版6.0中修复。
