### ISSUE TITLE
安装即将完成，initdata for bkdata() 一直hang住。

### ISSUE THREAD

**Issue by zjcnew** [TencentBlueKing/BKDocs#228]
![企业微信截图_20200508144248](https://user-images.githubusercontent.com/22335594/81378649-36b23200-913a-11ea-9c3b-fe46d4ae392c.png)

**Comment by shpdnkti** [comment]
更多问题请到蓝鲸社区版交流群咨询
- 点击链接加入群聊【蓝鲸社区版交流1群】：https://jq.qq.com/?_wv=1027&k=kvBYQGUe
