### ISSUE TITLE
ITSM服务API:/api/c/compapi/v2/itsm/get_tickets/ 有BUG

### ISSUE THREAD

**Issue by javaforrest** [TencentBlueKing/BKDocs#248]
传入任意的page参数，总是返回第一页数据

**Comment by shpdnkti** [comment]
分页的参数需要放到路径参数里，后续版本更新也支持post请求的。

---
更多问题请到蓝鲸社区版交流群咨询
- 点击链接加入群聊【蓝鲸社区版交流1群】：https://jq.qq.com/?_wv=1027&k=kvBYQGUe
