### ISSUE TITLE
下载项目地址不对

### ISSUE THREAD

**Issue by IvesFeng** [TencentBlueKing/BKDocs#256]
下载开发框架
下载开发框架 http://{PAAS_URL}/guide/newbie/#step3
{PAAS_URL} 为蓝鲸 PaaS 访问地址，例如 paas.blueking.com

怎么下载？？？

**Comment by shpdnkti** [comment]
可以到这里下载：
- 蓝鲸 SaaS 统一 Python 开发框架 V2 下载地址：https://bk.tencent.com/docs/document/6.0/149/6700
