### ISSUE TITLE
每次重启服务器后SaaS Applications 都要重新部署

### ISSUE THREAD

**Issue by asyowish** [TencentBlueKing/BKDocs#293]
Issue 仅用于文档 bug 跟进，其他问题欢迎到[蓝鲸 S-mart 问题社区](https://bk.tencent.com/s-mart/community)提问。

因是在笔记本工作站上3台虚机部署的（为方便联网），
三台4Cores+16G+50G的 CentOS 7.9，
一旦服务器重启（vm重启或笔记本重新开机），
./bkcli install saas-o
得这么再跑一遍才行，否则节点管理、监控平台……这些应用点击就是502。

**Comment by shpdnkti** [comment]
问题帮你转到了 [蓝鲸 S-mart 问题社区](https://bk.tencent.com/s-mart/community/)，后续非文档类问题欢迎到社区内提问。
---
https://bk.tencent.com/s-mart/community/question/2063

**Comment by shpdnkti** [comment]
此处问题应为，重启后 SaaS 未有自动拉起。社区版 6.0 版本 SaaS 运行与 docker 容器内，机器发生重启后，dockerd 服务 systemctl 拉起，但是 docker 内容器未有设置 restart 逻辑，可以手动使用命令` ./bkcli start saas-o `拉起 SaaS，无需重新部署。

或在 SaaS 部署脚本中增加 restart 逻辑：docker run xxx --restart=always xxx

详细请参考“机器重启”：https://bk.tencent.com/docs/document/6.0/127/7582
