### ISSUE TITLE
ZH/6.0/PaaS平台/产品白皮书/产品功能/开发者服务/DevServicesBaseEE.md中有用词不当的情况

### ISSUE THREAD

**Issue by XiangYing** [TencentBlueKing/BKDocs#494]
## 预期是什么
结合上下文，可能要表达的意思如下：
从而使 PaaS 平台之上的 SaaS 可以调度一**_切_**，连接一切。

## 当前是什么
从而使 PaaS 平台之上的 SaaS 可以调度一**_些_**，连接一切。

## 解决方案
参考预期

**Comment by shpdnkti** [comment]
@XiangYing fixed
