### ISSUE TITLE
单机部署文档调整

### ISSUE THREAD

**Issue by xiaoge888168** [TencentBlueKing/BKDocs#552]
1、https://bk.tencent.com/docs/document/6.0/127/7551，单机部署文档添加前言说明和建议配置
修改1：>单机部署仅作为部署体验用，建议管控主机10台以内

修改2：准备一台 CentOS 7.6 及以上操作系统的机器 (物理机和虚拟机均可，建议配置8C16G 100G硬盘)。

2、单机部署文档提到一级目录
![image](https://user-images.githubusercontent.com/39146216/166860597-168ec9e1-9c72-4208-a356-a55e817e9ac3.png)

**Comment by liuweijie1234** [comment]
已修改
