### ISSUE TITLE
新文档中心搜索的一些建议

### ISSUE THREAD

**Issue by baiyuchina** [TencentBlueKing/BKDocs#7]
1.建议增加下搜索结果的按时间排序，最后回复时间等维度的排序功能
2.建议对问答帖子增加蓝鲸版本，没有产品线的版本（不知道适不适合我当前的版本，建议提问题的时候加入蓝鲸的版本选择，展现在搜索结果上，不然4.x和5.x解决问题还是有区别的），包括以后的一些版本，如果帖子也没声明版本，也没有版本的标签，明明不适合的版本解决方案，也要自己尝试。
3.对帖子增加是否有人答复标签（采纳标签，最热标签等多标签），进帖子看了很久，发现问题也相似，但是没人回答过，很浪费浏览时间。
![image](https://user-images.githubusercontent.com/23309528/66821218-a7aeb400-ef74-11e9-861f-3a50f42c5278.png)
4.，蓝鲸社区写问答，我之前写个帖子，写了半天，它超时了，需要登录，当时我很心累，就放弃了写帖子。建议是不是自动每个多久保存一次，重新登录可以看到草稿并且重新写。或者在登录失效时，系统自动保存下。
5.啥时候能把群里ai蓝鲸的知识库也放入搜索就棒棒了

**Comment by TencentBlueKing** [comment]
感谢您的建议，这边评估下
