### ISSUE TITLE
gse 开源问题和安全问题咨询

### ISSUE THREAD

**Issue by zwz1995** [TencentBlueKing/BKDocs#853]
背景：项目上线需要遵循上线规范、规避安全风险。
1.想咨询一下您这边 gse agent是否有开源计划？多会儿开源？还是永久不开源？麻烦确切回答一下感谢
2.gse agent是否能提供安全性相关证明
3.目前agent安装过程中有安全相关的问题（存在反弹操作），能否解决
![image](https://user-images.githubusercontent.com/44857720/212228444-5fc1ac92-91a6-4a6b-8227-d121b9311386.png)

**Comment by shpdnkti** [comment]
Issues 与本项目内容无关，请前往论坛提交相关咨询： https://bk.tencent.com/s-mart/community/question
