### ISSUE TITLE
bk7.1的部署存在一个问题，ingressNginx.hostNetwork: true配置错误

### ISSUE THREAD

**Issue by houming818** [TencentBlueKing/BKDocs#923]
Issue 仅用于文档 bug 跟进，其他问题欢迎到[蓝鲸 S-mart 问题社区](https://bk.tencent.com/s-mart/community)提问。

bk7.1的部署存在一个问题，ingressNginx.hostNetwork: true配置错误。导致启动ingress始终是会和宿主机的80端口冲突。

## 当前是什么
![image](https://github.com/TencentBlueKing/BKDocs/assets/5498826/56b577bc-1f77-4e50-97d6-c3acb9b428fe)
![image](https://github.com/TencentBlueKing/BKDocs/assets/5498826/967b4e17-f724-4ec7-a20d-23592e566c40)
`~/bkce7.1-install/blueking/environments/default/values.yaml`这两个地方都配置了hostNetwork。
在deployment的chart中，~/bkce7.1-install/blueking/environments/default/bkingress-nginx-values.yaml.gotmpl：
![image](https://github.com/TencentBlueKing/BKDocs/assets/5498826/179708c5-83ab-41ab-9e18-14d61f303a63)

这里可以看到True的配置生效了。但是很多部署环境，宿主机的80端口都是被占用的。导致部署失败。

![1695559812100](https://github.com/TencentBlueKing/BKDocs/assets/5498826/8647baa3-bff1-4e99-baa2-823d3ec168c2)

**Comment by houming818** [comment]
建议把http的配置先从部署文档移除，因为https设置后，根本没办法部署成功。很多地方的证书都是自签证书。

**Comment by vuuv** [comment]
目前部署预期占用1-2个node的80端口。暂无调整计划。

因为考虑到证书问题，https目前并未推广，也没有时间投入梳理改造。且内部调用一般为http，只有用户浏览器入口才需要采购商业证书配置https。

**Comment by vuuv** [comment]
所以暂时不调整文档。如有其他需求，请重新打开issue。
